version: 2
jobs:
  build:
    machine: # for docker --privileged
      image: circleci/classic:latest
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Build & push Docker image tiliado/nuvolasdk-ci
          command: |
            if [ "$CIRCLE_BRANCH" = 'master' ]; then
                TAG=latest
            else
                TAG="$CIRCLE_BRANCH"
            fi
            IMAGE="tiliado/nuvolasdk-ci:$TAG"
            echo -e "\n\n~~~~ Building $IMAGE ~~~~\n"
            cd circleci-image
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t "$IMAGE" .
            docker push "$IMAGE"
