version: 2
jobs:
  build:
    machine: # for docker --privileged
      image: circleci/classic:latest
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Build Docker image tiliado/nuvolasdk-ci:$CIRCLE_BRANCH
          command: cd circleci-image && docker build -t tiliado/nuvolasdk-ci:$CIRCLE_BRANCH .
